version: "3.8"

services:
  frontend:
    container_name: stockd-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - stockd-network

networks:
  stockd-network:
    driver: bridge
