version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockd-backend
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - stockd-network
    restart: unless-stopped

networks:
  stockd-network:
    driver: bridge
    name: stockd-network
